version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: learn-rx-node
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "3000:3000"
      - "3001:3001"
    entrypoint:
      - /bin/sh
      - -c
      - yarn start
