version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000-3001:3000-3001"
    command: yarn start
